# See: https://docs.github.com/en/actions/writing-workflows
---
name: Update scoop bucket

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  update:
    name: Update
    runs-on: windows-latest
    steps:
      - name: Install scoop
        shell: pwsh
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
          irm get.scoop.sh | iex
          Join-Path (Resolve-Path ~).Path "scoop\shims" >> $env:GITHUB_PATH
      - name: Install hub
        run: scoop install hub
      - name: Setup git credentials
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Checkout scoop bucket
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_SCOOP_BUCKET }}
          repository: asimov-platform/scoop-bucket
      - name: Update
        shell: pwsh
        run: ./bin/auto-pr.ps1 -push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_SCOOP_BUCKET }}
